<?php

require_once __DIR__ . '/vendor/autoload.php';

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__ . '/');
$dotenv->load();

define('DATABASE_NAME', $_SERVER['DATABASE_NAME'] ?? "");
define('DATABASE_USERNAME', $_SERVER['DATABASE_USERNAME'] ?? "");
define('DATABASE_PASSWORD', $_SERVER['DATABASE_PASSWORD'] ?? "");
define('DATABASE_HOST', $_SERVER['DATABASE_HOST'] ?? "");
define('DATABASE_CHARSET', $_SERVER['DATABASE_CHARSET'] ?? "");
define('WP_ENABLED_DEBUG_MODE', $_SERVER['WP_ENABLED_DEBUG_MODE'] ?? "");
define('WP_DEBUG_LOG_FILE', $_SERVER['WP_DEBUG_LOG_FILE']);
define('WP_ENABLED_DEBUG_DISPLAY', $_SERVER['WP_ENABLED_DEBUG_DISPLAY']);
define('_2C2P_HOST', $_SERVER['_2C2P_HOST'] ?? "");
define('_2C2P_MERCHANT_ID', $_SERVER['_2C2P_MERCHANT_ID'] ?? "");
define('_2C2P_SECRET_AUTH_KEY', $_SERVER['_2C2P_SECRET_AUTH_KEY'] ?? "");
define('_2C2P_SECRET_SHA_KEY', $_SERVER['_2C2P_SECRET_SHA_KEY'] ?? "");
define('_2C2P_REDIRECT_BACKEND_URL', $_SERVER['_2C2P_REDIRECT_BACKEND_URL'] ?? "");
define('_2C2P_REDIRECT_FRONTEND_URL', $_SERVER['_2C2P_REDIRECT_FRONTEND_URL'] ?? "");
define('_2C2P_ENABLED_REDIRECT_NOTIFICATION_DEFAULT', $_SERVER['_2C2P_ENABLED_REDIRECT_NOTIFICATION_DEFAULT'] ?? "");
define('ENABLED_REDIRECT_CHECKOUT_PAYMENT_URL', $_SERVER['ENABLED_REDIRECT_CHECKOUT_PAYMENT_URL']);
define('ENABLED_USING_WOO_PRODUCT_ID_REPLACED', $_SERVER['ENABLED_USING_WOO_PRODUCT_ID_REPLACED']);
define('REDIRECT_LINK_ORDER_COMPLETED', $_SERVER['REDIRECT_LINK_ORDER_COMPLETED']);
define('REDIRECT_LINK_ORDER_FAILURE', $_SERVER['REDIRECT_LINK_ORDER_FAILURE']);
define('VIRTUAL_SANDBOX_CUSTOMER_NAME', $_SERVER['VIRTUAL_SANDBOX_CUSTOMER_NAME'] ?? "");
define('VIRTUAL_SANDBOX_CUSTOMER_EMAIL', $_SERVER['VIRTUAL_SANDBOX_CUSTOMER_EMAIL'] ?? "");
define('VIRTUAL_SANDBOX_CUSTOMER_PHONE', $_SERVER['VIRTUAL_SANDBOX_CUSTOMER_PHONE'] ?? "");
define('VIRTUAL_SANDBOX_PRODUCT_ID', intval($_SERVER['VIRTUAL_SANDBOX_PRODUCT_ID'] ?? 0));
define('VIRTUAL_SANDBOX_PRODUCT_NAME', $_SERVER['VIRTUAL_SANDBOX_PRODUCT_NAME'] ?? "");
define('VIRTUAL_SANDBOX_OFFER_ID', intval($_SERVER['VIRTUAL_SANDBOX_OFFER_ID'] ?? 0));
define('VIRTUAL_SANDBOX_PROVINCE_NAME', $_SERVER['VIRTUAL_SANDBOX_PROVINCE_NAME'] ?? "");
define('VIRTUAL_SANDBOX_DISTRICT_NAME', $_SERVER['VIRTUAL_SANDBOX_DISTRICT_NAME'] ?? "");
define('VIRTUAL_SANDBOX_WARD_NAME', $_SERVER['VIRTUAL_SANDBOX_WARD_NAME'] ?? "");
define('VIRTUAL_SANDBOX_SHIPPING_ADDRESS', $_SERVER['VIRTUAL_SANDBOX_SHIPPING_ADDRESS'] ?? "");
define('VIRTUAL_SANDBOX_PROVINCE_ID', intval($_SERVER['VIRTUAL_SANDBOX_PROVINCE_ID'] ?? 0));
define('VIRTUAL_SANDBOX_DISTRICT_ID', intval($_SERVER['VIRTUAL_SANDBOX_DISTRICT_ID'] ?? 0));
define('VIRTUAL_SANDBOX_WARD_ID', intval($_SERVER['VIRTUAL_SANDBOX_WARD_ID'] ?? 0));
define('VIRTUAL_SANDBOX_ENABLED_GENERATE_CLICK_ID', $_SERVER['VIRTUAL_SANDBOX_ENABLED_GENERATE_CLICK_ID'] ?? "");
define('VIRTUAL_SANDBOX_LINK', $_SERVER['VIRTUAL_SANDBOX_LINK'] ?? "");
define('VIRTUAL_SANDBOX_TRACKER_ID', $_SERVER['VIRTUAL_SANDBOX_TRACKER_ID'] ?? 0);
?>